#!/bin/bash

# Injects disk IO errors on devices permitted by setting
# /sys/block/<device>/make-it-fail or
# /sys/block/<device>/<partition>/make-it-fail. (generic_make_request())
#
# NOTE: This causes the filesystem to be remounted as readonly,
# if errors=remount-ro is set in /etc/fstab.
# If so, the filesystem can only be recovered by a reboot.
# Running 'mount -no remount,rw /' may not work.

device=sda

FAILTYPE=fail_make_request
echo N > /sys/kernel/debug/$FAILTYPE/task-filter
echo 50 > /sys/kernel/debug/$FAILTYPE/probability
echo 10 > /sys/kernel/debug/$FAILTYPE/interval
echo -1 > /sys/kernel/debug/$FAILTYPE/times
echo 0 > /sys/kernel/debug/$FAILTYPE/space
echo 2 > /sys/kernel/debug/$FAILTYPE/verbose
#echo 1 > /sys/kernel/debug/$FAILTYPE/ignore-gfp-wait

faulty_system()
{
#	bash -c "echo 1 > /proc/self/make-it-fail && exec $*"
	echo 1 > /sys/block/$device/make-it-fail
}

#if [ $# -eq 0 ]
#then
	#echo "Usage: $0 modulename [ modulename ... ]"
#	echo "Usage: $0 device [ device ... ]"
#	exit 1
#fi

#for m in $*
#do
#	echo inserting $m...
#	faulty_system $m

#	echo removing $m...
	#faulty_system $m
#done

faulty_system

trap "echo 0 > /sys/kernel/debug/$FAILTYPE/probability" SIGINT SIGTERM EXIT

echo "Injecting errors into the disk... (interrupt to stop)"
sleep 1000000

